### ISSUE TITLE
Can't Create New Disasters

### ISSUE THREAD

**Issue by Taylor3621** [CajunAvenger/LackeyBot#35]
Hey there! It seems like no one is able to create new disasters for LackeyBot. Whenever I try, it says the application isn't responding.
![Screenshot_20240428-201551](https://github.com/CajunAvenger/LackeyBot/assets/107843203/542ce1ea-be78-40a7-b4d2-9bdcc11f9b5a)

**Comment by CajunAvenger** [comment]
fixed on live
